const due = "2026-08-03T18:00:00+02:00";

export const fixture = {
  is_admin: true,
  people: {
    dominik: {
      name: "Dominik mit einem bewusst langen Anzeigenamen",
      notify: "notify.mobile_app_iphone_von_dominik",
      presence: "person.admin",
      user_id: "user-dominik",
      home: true,
    },
    alina: {
      name: "Alina",
      notify: "notify.mobile_app_iphone_von_alina",
      presence: "person.alina",
      user_id: "user-alina",
      home: false,
    },
  },
  tasks: {
    frostschutz: {
      enabled: true,
      name: "Frostschutz beim eigenen Auto prüfen",
      description: "Vor dem ersten Frost Kühlmittel und Scheibenwaschanlage prüfen.",
      assignee: "dominik",
      assignment: { type: "fixed", people: ["dominik", "alina"] },
      schedule: { type: "manual" },
      checklist: [{ id: "coolant", title: "Kühlmittel kontrollieren" }],
      market: { priority: "high", points: 3, reward: "" },
      nfc: { tag_id: "car-frost", action: "create_or_complete" },
    },
    waste: {
      enabled: true,
      name: "Gelbe Tonne rausstellen",
      assignee: "alina",
      assignment: { type: "rotation", people: ["dominik", "alina"] },
      schedule: { type: "calendar", entity_id: "calendar.waste" },
    },
  },
  occurrences: [
    {
      id: "open-frost",
      task_id: "frostschutz",
      title: "[Dominik] Frostschutz beim eigenen Auto prüfen",
      assignee: "dominik",
      due,
      status: "open",
      resolved: false,
      revision: 2,
      checklist: [{ id: "coolant", title: "Kühlmittel kontrollieren", completed: false }],
      task: {
        description: "Vor dem ersten Frost Kühlmittel und Scheibenwaschanlage prüfen.",
        require_checklist_completion: true,
        market: { priority: "high", points: 3 },
      },
      assignment_reason: { type: "fixed", selected: "dominik" },
    },
    {
      id: "done-waste",
      task_id: "waste",
      title: "[Alina] Gelbe Tonne rausstellen",
      assignee: "alina",
      completed_by: "alina",
      due: "2026-07-28T18:00:00+02:00",
      status: "completed",
      resolved: true,
      resolved_at: "2026-07-28T18:12:00+02:00",
      created_at: "2026-07-27T18:00:00+02:00",
      revision: 4,
      checklist: [],
      task: { description: "Gelbe Tonne am Vorabend bereitstellen." },
    },
  ],
  attachments: {
    "done-waste": [{ id: "proof-1", name: "tonne.jpg", mime_type: "image/jpeg", size: 5_000_000 }],
  },
  task_events: [],
  scores: { dominik: 8, alina: 5 },
  task_stacks: { evening: { name: "Abendrunde", task_ids: ["waste"] } },
  home_context: { title: "Vor dem Abendessen", occurrence_ids: ["open-frost"] },
  household_mode: { mode: "normal" },
  defaults: { escalation: [] },
  monitors: {},
  undo: [],
  week_preview: [],
  analytics: {},
  health: { status: "ok", findings: [] },
};
